
CREATE TABLE client (
  ID integer not null GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  first_name varchar(255) DEFAULT NULL,
  second_name varchar(255) DEFAULT NULL,
  active INT DEFAULT 0,
  birth_date DATE,
  PRIMARY KEY (ID)
);

CREATE TABLE city (
                      ID integer not null GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  name varchar(255) DEFAULT NULL,
  latitude DECIMAL(10, 6),
  longitude DECIMAL(10, 6),
  PRIMARY KEY (ID)
);

CREATE TABLE client_city (
  clientId int NOT NULL,
  cityId int NOT NULL,
  PRIMARY KEY (clientId,cityId)
);

CREATE TABLE other (
  something int NOT NULL
);

COMMIT;
