
declare l_c CURSOR;
BEGIN

    INSERT INTO CLIENT (ID, FIRST_NAME, SECOND_NAME, BIRTH_DATE) VALUES (2, 'Ester', 'Colero', date '2000-01-02');
    INSERT INTO CITY (ID, NAME, LATITUDE, LONGITUDE) SELECT 2, 'Madrid', 40.416775, -3.703790 FROM DUAL;
    open l_c for SELECT * FROM CLIENT;
    UPDATE CLIENT SET ACTIVE = 0 WHERE ID = 1;
    INSERT INTO CLIENT_CITY (CLIENTID, CITYID) VALUES (2, 2);
    INSERT INTO CLIENT_CITY (CLIENTID, CITYID) VALUES (2, 1);

END;
