version: 2
jobs:

  build-configurer:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/wakamiti/configurer
    steps:
      - checkout
      - restore_cache:
          key: wakamiti-{{ checksum "pom.xml" }}
      - save_cache:
          paths:
            - ~/.m2
          key: wakamiti-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports


  build-jplugin:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/wakamiti/jext
    steps:
      - checkout
      - restore_cache:
          key: wakamiti-{{ checksum "pom.xml" }}
      - save_cache:
          paths:
            - ~/.m2
          key: wakamiti-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports

  build-core:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/wakamiti/wakamiti-core
    steps:
      - checkout
      - restore_cache:
          key: wakamiti-{{ checksum "pom.xml" }}
      - save_cache:
          paths:
            - ~/.m2
          key: wakamiti-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-configurer
      - build-jext
      - build-core


