/*
 * Copyright (c) 2022-2026 Instituto Tecnológico de Informática (ITI)
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */
package es.iti.wakamiti.test.gherkin;


import static es.iti.wakamiti.api.WakamitiConfiguration.STRICT_TEST_CASE_ID;
import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.stream.Collectors;

import org.json.JSONException;
import org.junit.ComparisonFailure;
import org.junit.Test;
import org.skyscreamer.jsonassert.JSONCompare;
import org.skyscreamer.jsonassert.JSONCompareMode;
import org.skyscreamer.jsonassert.JSONCompareResult;
import org.skyscreamer.jsonassert.comparator.DefaultComparator;
import org.skyscreamer.jsonassert.comparator.JSONComparator;
import org.slf4j.Logger;

import es.iti.wakamiti.api.WakamitiConfiguration;
import es.iti.wakamiti.api.WakamitiException;
import es.iti.wakamiti.api.imconfig.Configuration;
import es.iti.wakamiti.api.imconfig.ConfigurationException;
import es.iti.wakamiti.api.plan.NodeType;
import es.iti.wakamiti.api.plan.PlanNode;
import es.iti.wakamiti.api.plan.PlanNodeSnapshot;
import es.iti.wakamiti.api.plan.Result;
import es.iti.wakamiti.api.util.WakamitiLogger;
import es.iti.wakamiti.core.Wakamiti;
import es.iti.wakamiti.core.gherkin.GherkinPlanBuilder;
import es.iti.wakamiti.core.gherkin.GherkinResourceType;


public class TestPlanFactory {

    private static final Logger LOGGER = WakamitiLogger.forName("es.iti.wakamiti.test");

    private void assertFilePlan(
            String filename,
            int testCases
    ) throws IOException, JSONException, ConfigurationException {
        String featureFilename = "src/test/resources/features/" + filename + ".feature";
        String resultFilename = "src/test/resources/features/" + filename + "_plan.json";
        assertFilePlan(featureFilename, resultFilename, null, testCases);
    }

    private void assertFilePlan(
            String featureFilename,
            String resultFilename,
            String tagExpression,
            int testCases
    ) throws IOException, JSONException, ConfigurationException {
        assertPlan(featureFilename, resultFilename, tagExpression, testCases, new Properties());
    }

    private void assertPathPlan(
            String featurePath,
            String resultFilename,
            String tagExpression,
            int testCases
    ) throws IOException, JSONException, ConfigurationException {
        assertPlan(featurePath, resultFilename, tagExpression, testCases, new Properties());
    }

    private void assertPlan(
            String path,
            String resultFilename,
            String tagExpression,
            int testCases,
            Properties extraProperties
    ) throws JSONException, IOException, ConfigurationException {
        Properties properties = new Properties();
        properties.put(WakamitiConfiguration.RESOURCE_TYPES, GherkinResourceType.NAME);
        properties.put(WakamitiConfiguration.RESOURCE_PATH, path);
        properties.put(WakamitiConfiguration.OUTPUT_FILE_PATH, "target/" + Path.of(resultFilename).getFileName());
        properties.putAll(extraProperties);
        if (tagExpression != null) {
            properties.put(WakamitiConfiguration.TAG_FILTER, tagExpression);
        }
        Configuration configuration = Wakamiti.defaultConfiguration()
                .appendFromProperties(properties);
        Wakamiti wakamiti = Wakamiti.instance();
        PlanNode testPlan = wakamiti.createPlanFromConfiguration(configuration);
        if (LOGGER.isDebugEnabled()) {
            System.out.println(printPlan(testPlan, new StringBuilder(), 0));
        }
        wakamiti.writeOutputFile(testPlan, configuration);

        assertThat(testPlan.numDescendants(NodeType.TEST_CASE)).isEqualTo(testCases);

        String plan = Wakamiti.planSerializer().serialize(testPlan);
        // remove autogenerated ids because they change on each execution
        plan = plan.replaceAll("\\[#.*]", "[]");
        String expectedResult = Wakamiti.resourceLoader().readResourceAsString(resultFilename);
        JSONComparator comparator = new DefaultComparator(JSONCompareMode.STRICT_ORDER);
        JSONCompareResult comparison = JSONCompare.compareJSON(expectedResult, plan, comparator);
        if (comparison.failed()) {
            throw new ComparisonFailure(comparison.getMessage(), expectedResult, plan);
        }
    }

    private PlanNode runPlan(
            String path,
            String resultFilename
    ) throws ConfigurationException {
        return runPlan(path, resultFilename, Configuration.factory().empty());
    }

    private PlanNode runPlan(
            String path,
            String resultFilename,
            Configuration extraConfig
    ) {
        Properties properties = new Properties();
        properties.put(WakamitiConfiguration.RESOURCE_TYPES, GherkinResourceType.NAME);
        properties.put(WakamitiConfiguration.RESOURCE_PATH, path);
        properties.put(WakamitiConfiguration.OUTPUT_FILE_PATH, "target/" + Path.of(resultFilename).getFileName());
        Configuration configuration = Wakamiti.defaultConfiguration()
                .appendFromProperties(properties)
                .append(extraConfig);
        Wakamiti wakamiti = Wakamiti.instance();
        PlanNode testPlan = wakamiti.createPlanFromConfiguration(configuration);
        testPlan = wakamiti.executePlan(testPlan, configuration);
        if (LOGGER.isDebugEnabled()) {
            System.out.println(printPlan(testPlan, new StringBuilder(), 0));
        }
        return testPlan;
    }

    private PlanNode createPlan(
            String path,
            Configuration extraConfig
    ) {
        Properties properties = new Properties();
        properties.put(WakamitiConfiguration.RESOURCE_TYPES, GherkinResourceType.NAME);
        properties.put(WakamitiConfiguration.RESOURCE_PATH, path);
        Configuration configuration = Wakamiti.defaultConfiguration()
                .appendFromProperties(properties)
                .append(extraConfig);
        return Wakamiti.instance().createPlanFromConfiguration(configuration);
    }

    @Test
    public void test1SimpleScenario() throws IOException, JSONException, ConfigurationException {
        assertFilePlan("test1_simpleScenario", 1);
    }

    @Test
    public void test2ScenarioOutline() throws IOException, JSONException, ConfigurationException {
        assertFilePlan("test2_scenarioOutline", 3);
    }

    @Test
    public void test3Background() throws IOException, JSONException, ConfigurationException {
        assertFilePlan("test3_background", 3);
    }

    @Test
    public void test4TagExpression() throws IOException, JSONException, ConfigurationException {
        assertFilePlan(
                "src/test/resources/features/test4_tagExpression.feature",
                "src/test/resources/features/test4_tagExpression_plan.json",
                "Test4 and (b and (@C or @d))",
                1
        );
    }

    @Test
    public void test5IncludeFilteredTestCases() throws IOException, JSONException, ConfigurationException {
        Properties properties = new Properties();
        properties.put(WakamitiConfiguration.INCLUDE_FILTERED_TEST_CASES, "true");
        assertPlan(
                "src/test/resources/features/test5_includeFiltered.feature",
                "src/test/resources/features/test5_includeFiltered_plan.json",
                "Test5 and A",
                2,
                properties
        );
    }

    @Test
    public void test6PropertySubstitution() throws IOException, JSONException, ConfigurationException {
        Properties properties = new Properties();
        properties.put("number.a", "8.02");
        properties.put("number.b", "9");
        properties.put("number.c", "72.18");
        properties.put("operation", "multiplied");

        assertPlan(
                "src/test/resources/features/test6_propertySubstitution.feature",
                "src/test/resources/features/test6_propertySubstitution_plan.json",
                "",
                1,
                properties
        );
    }

    @Test
    public void test7LifecycleHooks() throws ConfigurationException {
        PlanNode plan = createPlan(
                "src/test/resources/features/test7_lifecycleHooks.feature",
                Configuration.factory().fromPairs(WakamitiConfiguration.TAG_FILTER, "ID-Test7")
        );
        PlanNode feature = plan.children().findFirst().orElseThrow();

        List<PlanNode> lifecycleScenarios = feature.children()
                .filter(child -> child.nodeType() == NodeType.LIFECYCLE_HOOK)
                .toList();

        assertThat(lifecycleScenarios).hasSize(2);
        assertThat(lifecycleScenarios).allMatch(node -> !node.displayName().startsWith("["));
        assertThat(lifecycleScenarios).extracting(node -> node.properties().get(GherkinPlanBuilder.GHERKIN_PROPERTY))
                .containsExactly("before", "after");
        assertThat(lifecycleScenarios).allMatch(node ->
                "Test 7 - Lifecycle hooks".equals(node.properties().get(GherkinPlanBuilder.GHERKIN_FEATURE_NAME)));
        assertThat(lifecycleScenarios).allMatch(node -> node.children().anyMatch(
                child -> GherkinPlanBuilder.GHERKIN_TYPE_STEP.equals(
                        child.properties().get(GherkinPlanBuilder.GHERKIN_PROPERTY))));
        assertThat(lifecycleScenarios).allMatch(node -> node.children()
                .noneMatch(child -> GherkinPlanBuilder.GHERKIN_TYPE_BACKGROUND.equals(
                        child.properties().get(GherkinPlanBuilder.GHERKIN_PROPERTY)
                )));
        assertThat(feature.children()
                .filter(node -> node.nodeType() == NodeType.TEST_CASE)
                .count()).isEqualTo(1);
    }

    @Test
    public void test7LifecycleHooksAreRetainedWhenFeatureIsFilteredOut() throws ConfigurationException {
        PlanNode plan = createPlan(
                "src/test/resources/features/test7_lifecycleHooks.feature",
                Configuration.factory().fromPairs(WakamitiConfiguration.TAG_FILTER, "NonExistingTag")
        );
        PlanNode feature = plan.children().findFirst().orElseThrow();

        List<PlanNode> lifecycleScenarios = feature.children()
                .filter(child -> child.nodeType() == NodeType.LIFECYCLE_HOOK)
                .toList();

        assertThat(lifecycleScenarios).hasSize(2);
        assertThat(feature.children()
                .filter(node -> node.nodeType() == NodeType.TEST_CASE)
                .count()).isEqualTo(0);
    }

    @Test
    public void test7LifecycleHooksDoNotRequireStrictId() {
        PlanNode plan = createPlan(
                "src/test/resources/features/test7_lifecycleHooks.feature",
                Configuration.factory().fromPairs(
                        WakamitiConfiguration.TAG_FILTER, "ID-Test7",
                        STRICT_TEST_CASE_ID, "true"
                )
        );

        PlanNode feature = plan.children().findFirst().orElseThrow();
        assertThat(feature.children()
                .filter(node -> node.nodeType() == NodeType.LIFECYCLE_HOOK)
                .count()).isEqualTo(2);
    }

    @Test(expected = WakamitiException.class)
    public void testLifecycleReservedTagsAreRejectedInScenarioOutline() {
        try {
            createPlan(
                    "src/test/resources/features/failure/lifecycleOutline.feature",
                    Configuration.factory().empty()
            );
        } catch (Exception e) {
            assertThat(e).hasMessageContaining("Reserved lifecycle tags are not supported in Scenario Outline");
            throw e;
        }
    }

    @Test(expected = WakamitiException.class)
    public void testMultipleLifecycleReservedTagsAreRejected() {
        try {
            createPlan(
                    "src/test/resources/features/failure/multipleLifecycleTags.feature",
                    Configuration.factory().empty()
            );
        } catch (Exception e) {
            assertThat(e).hasMessageContaining("Only one lifecycle reserved tag is allowed");
            throw e;
        }
    }

    @Test
    public void testLifecycleHooks() {
        PlanNode plan = runPlan(
                "src/test/resources/features/lifecycleHooks",
                "test7_lifecycleHooks_plan.json",
                Configuration.factory().fromPairs(
                        WakamitiConfiguration.NON_REGISTERED_STEP_PROVIDERS,
                        "es.iti.wakamiti.test.gherkin.WakamitiSteps"
                )
        );
        PlanNodeSnapshot snapshot = new PlanNodeSnapshot(plan);

        assertThat(snapshot.getResult()).isEqualTo(Result.PASSED);
        assertThat(snapshot.getTestCaseResults()).isEqualTo(Map.of(Result.PASSED, 1L));
        assertThat(snapshot.getChildrenResults()).isEqualTo(Map.of(Result.PASSED, 1L));
    }

    @Test
    public void testRedefining() throws IOException, JSONException, ConfigurationException {
        assertPathPlan(
                "src/test/resources/features/redefining",
                "src/test/resources/features/redefining/redefining_plan.json",
                null,
                4
        );
    }

    @Test
    public void testNotImplemented() {
        PlanNode plan = runPlan(
                "src/test/resources/features/notImplemented",
                "notImplemented_plan.json"
        );

        assertThat(plan.result().isPresent()).isTrue();
        assertThat(plan.result().get()).isEqualTo(Result.NOT_IMPLEMENTED);
        assertThat(plan.displayName()).isEqualTo("Test Plan");
        assertThat(plan.startInstant().isPresent()).isTrue();
        assertThat(plan.finishInstant().isPresent()).isTrue();
    }

    @Test
    public void testEmpty() {
        PlanNode plan = runPlan(
                "src/test/resources/features/empty.feature",
                "empty_plan.json"
        );

        assertThat(plan.result()).isNotPresent();
    }

    @Test
    public void testWithoutChildren() {
        PlanNode plan = runPlan(
                "src/test/resources/features/noChildren.feature",
                "empty_plan.json"
        );

        assertThat(plan.result()).isNotPresent();
    }

    @Test
    public void testStrictID() {
        PlanNode plan = runPlan(
                "src/test/resources/features/notImplemented/definition.feature",
                "strictID.json",
                Configuration.factory().fromPairs(
                        STRICT_TEST_CASE_ID, "true"
                )
        );

        assertThat(plan.result()).isPresent();
    }

    @Test
    public void testWhenNoExecution() throws IOException, JSONException {
        String resultFilename = "src/test/resources/features/noExecution.json";

        Properties properties = new Properties();
        properties.put(WakamitiConfiguration.RESOURCE_TYPES, GherkinResourceType.NAME);
        properties.put(WakamitiConfiguration.RESOURCE_PATH, "src/test/resources/features/noExecution.feature");
        properties.put(WakamitiConfiguration.OUTPUT_FILE_PATH, "target/" + Path.of(resultFilename).getFileName());
        properties.put(
                WakamitiConfiguration.NON_REGISTERED_STEP_PROVIDERS,
                "es.iti.wakamiti.test.gherkin.WakamitiSteps"
        );
        properties.put(WakamitiConfiguration.DRY_RUN, "true");
        Configuration configuration = Wakamiti.defaultConfiguration()
                .appendFromProperties(properties);
        Wakamiti wakamiti = Wakamiti.instance();
        PlanNode testPlan = wakamiti.createPlanFromConfiguration(configuration);
        testPlan = wakamiti.executePlan(testPlan, configuration);
        if (LOGGER.isDebugEnabled()) {
            System.out.println(printPlan(testPlan, new StringBuilder(), 0));
        }
        wakamiti.writeOutputFile(testPlan, configuration);

        assertThat(testPlan.numDescendants(NodeType.TEST_CASE)).isEqualTo(3);

        String plan = Wakamiti.planSerializer().serialize(testPlan);
        // remove autogenerated ids because they change on each execution
        plan = plan.replaceAll("\\[#.*]", "[]");
        String expectedResult = Wakamiti.resourceLoader().readResourceAsString(resultFilename);
        JSONComparator comparator = new DefaultComparator(JSONCompareMode.STRICT_ORDER);
        JSONCompareResult comparison = JSONCompare.compareJSON(expectedResult, plan, comparator);
        if (comparison.failed()) {
            throw new ComparisonFailure(comparison.getMessage(), expectedResult, plan);
        }
    }

    @Test(expected = WakamitiException.class)
    public void testStrictIDWhenError() {
        runPlan(
                "src/test/resources/features/strictID.feature",
                "strictID_error.json",
                Configuration.factory().fromPairs(
                        STRICT_TEST_CASE_ID, "true"
                )
        );
    }

    @Test(expected = WakamitiException.class)
    public void testScenarioOutlineWhenNoExamplesTableWithError() {
        try {
            runPlan(
                    "src/test/resources/features/failure/outline.feature",
                    "error.json"
            );
        } catch (Exception e) {
            assertThat(e).hasMessage("Example table is needed at scenario: src/test/resources/features/failure/outline.feature[7,3].");
            throw e;
        }
    }

    @Test(expected = WakamitiException.class)
    public void testPlanWhenParserError() {
        try {
            runPlan(
                    "src/test/resources/features/failure/parse.feature",
                    "error.json"
            );
        } catch (Exception e) {
            assertThat(e)
                    .hasMessageContaining("parse.feature': Parser errors:")
                    .hasMessageContaining("(1:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got '```gherkin'");
            throw e;
        }
    }

    private StringBuilder printPlan(
            PlanNode node,
            StringBuilder string,
            int level
    ) {
        StringBuilder leading = new StringBuilder();
        leading.append("--".repeat(Math.max(0, level)));
        leading.append("  ").append(node.nodeType()).append("  >> ").append(node.displayName());
        string.append(
                String.format(
                        "%-100s %-40s %s%n",
                        leading,
                        node.tags().isEmpty() ? "" : node.tags().stream().sorted().map(s -> "#" + s).collect(Collectors.joining(" ")),
                        node.properties().isEmpty() ? "" : node.properties()
                )
        );
        node.children().forEach(child -> printPlan(child, string, level + 1));
        return string;
    }

}
