// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.3,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model;

/**
 * Repository contains the information needed for deploying to the
 * remote
 *         repository.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class DeploymentRepository
    extends Repository
    implements java.io.Serializable, java.lang.Cloneable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Whether to assign snapshots a unique version comprised of
     * the timestamp and
     *             build number, or to use the same version each
     * time.
     */
    private boolean uniqueVersion = true;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method clone.
     * 
     * @return DeploymentRepository
     */
    public DeploymentRepository clone()
    {
        try
        {
            DeploymentRepository copy = (DeploymentRepository) super.clone();

            return copy;
        }
        catch ( java.lang.Exception ex )
        {
            throw (java.lang.RuntimeException) new java.lang.UnsupportedOperationException( getClass().getName()
                + " does not support clone()" ).initCause( ex );
        }
    } //-- DeploymentRepository clone()

    /**
     * Get whether to assign snapshots a unique version comprised
     * of the timestamp and
     *             build number, or to use the same version each
     * time.
     * 
     * @return boolean
     */
    public boolean isUniqueVersion()
    {
        return this.uniqueVersion;
    } //-- boolean isUniqueVersion()

    /**
     * Set whether to assign snapshots a unique version comprised
     * of the timestamp and
     *             build number, or to use the same version each
     * time.
     * 
     * @param uniqueVersion
     */
    public void setUniqueVersion( boolean uniqueVersion )
    {
        this.uniqueVersion = uniqueVersion;
    } //-- void setUniqueVersion( boolean )

}
