// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.8.3,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model;

/**
 * A PatternSet for files.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class FileSet
    extends PatternSet
    implements java.io.Serializable, java.lang.Cloneable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Describe the directory where the resources are stored. The
     * path is relative
     *             to the POM.
     */
    private String directory;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method clone.
     * 
     * @return FileSet
     */
    public FileSet clone()
    {
        try
        {
            FileSet copy = (FileSet) super.clone();

            return copy;
        }
        catch ( java.lang.Exception ex )
        {
            throw (java.lang.RuntimeException) new java.lang.UnsupportedOperationException( getClass().getName()
                + " does not support clone()" ).initCause( ex );
        }
    } //-- FileSet clone()

    /**
     * Get describe the directory where the resources are stored.
     * The path is relative
     *             to the POM.
     * 
     * @return String
     */
    public String getDirectory()
    {
        return this.directory;
    } //-- String getDirectory()

    /**
     * Set describe the directory where the resources are stored.
     * The path is relative
     *             to the POM.
     * 
     * @param directory
     */
    public void setDirectory( String directory )
    {
        this.directory = directory;
    } //-- void setDirectory( String )

    
            
    /**
     * @see java.lang.Object#toString()
     */
    public String toString()
    {
        return "FileSet {directory: " + getDirectory() + ", " + super.toString() + "}";
    }
            
          
}
