/*
 * Copyright (c) 2022-2026 Instituto Tecnológico de Informática (ITI)
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */
package ${package};


import es.iti.commons.jext.Extension;
import es.iti.wakamiti.api.annotations.I18nResource;
import es.iti.wakamiti.api.annotations.Step;
import es.iti.wakamiti.api.extensions.StepContributor;
import es.iti.wakamiti.api.util.WakamitiLogger;
import org.slf4j.Logger;


/**
 * Template step contributor generated by the Wakamiti plugin archetype.
 * <p>
 * Replace sample steps with domain-specific step definitions and keep method
 * Javadocs aligned with behavior, parameters and expected failures.
 * </p>
 */
@Extension(
        provider = "es.iti.wakamiti",
        name = "${pluginId}",
        version = "2.6"
)
@I18nResource("es_iti_wakamiti_${pluginId}")
public class ${PluginId}StepContributor implements StepContributor {

    private final Logger logger = WakamitiLogger.forClass(${PluginId}StepContributor.class);

    // the following is an example of step definitions

    /**
     * Example step definition placeholder.
     */
    @Step("${pluginId}.step1")
    public void step1 () {
        //
    }

    /**
     * Example step definition placeholder.
     */
    @Step("${pluginId}.step2")
    public void step2 () {
        //
    }

    /**
     * Example step definition placeholder.
     */
    @Step("${pluginId}.step3")
    public void step3 () {
        //
    }

}
