/*
 * Copyright (c) 2022-2026 Instituto Tecnológico de Informática (ITI)
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */
package ${package};


import es.iti.wakamiti.api.imconfig.Configuration;
import es.iti.wakamiti.api.imconfig.Configurer;
import es.iti.commons.jext.Extension;
import es.iti.wakamiti.api.extensions.ConfigContributor;


/**
 * Template configuration contributor generated by the plugin archetype.
 * <p>
 * It defines default properties and contributes contributor-specific
 * configuration logic for {@code ${PluginId}StepContributor}.
 * </p>
 */
@Extension(
        provider = "es.iti.wakamiti",
        name = "${pluginId}-config",
        version = "2.6",
        extensionPoint = "es.iti.wakamiti.api.extensions.ConfigContributor"
)
public class ${PluginId}ConfigContributor implements ConfigContributor<${PluginId}StepContributor>{

    private static final Configuration DEFAULTS = Configuration.factory().fromPairs(
            "${pluginId}.property1", "value1"
    );

    /**
     * Indicates whether this contributor can configure the supplied object.
     *
     * @param contributor candidate contributor instance
     * @return {@code true} when the object is a ${PluginId}StepContributor
     */
    @Override
    public boolean accepts(
            Object contributor
    ) {
        return contributor instanceof ${PluginId}StepContributor;
    }

    /**
     * Returns default configuration values contributed by this plugin.
     *
     * @return default plugin configuration
     */
    @Override
    public Configuration defaultConfiguration() {
        return DEFAULTS;
    }

    /**
     * Returns the configurator callback used by Wakamiti.
     *
     * @return contributor configurator
     */
    @Override
    public Configurer<${PluginId}StepContributor> configurer() {
        return this::configure;
    }

    private void configure(
            ${PluginId}StepContributor contributor,
            Configuration configuration
    ){
            // TODO
    }

}
