= Kukumo::Database Steps
:icons: font

This plugin provides a set of steps that interact with a database via JDBC, easing the effort
required to load and assert data.

Data set can be defined in different ways:

- From CSV files, for a single table
- From XLSX files, for multiple tables
- From data tables included directly in the document, using the format:

```gherkin
 | columnA | columnB | columnC |
 | row1A   | row1B   | row1C   |
 | row2A   | row2B   | row2C   |
```



The plugin source code provides a convenient way to implement new data sources extending the abstract
class `DataSet`, which can be used by third-party contributors.


CAUTION: Regarding the multiple database implementations existing, this plugin _does not_ include
any specific driver. In order to work properly, remember to include the module with the JDBC driver(s)
that your database connection would require.

---

== Usage

=== Configuration properties

CAUTION:  These properties must have the `kukumo.` prefix when defined in an external configuration file.

include::configuration.adoc[]

=== Steps

include::steps.adoc[]

