<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>es.iti.wakamiti</groupId>
        <artifactId>wakamiti-starter</artifactId>
        <version>1.3.0</version>
        <relativePath>../wakamiti-starter</relativePath>
    </parent>

    <artifactId>wakamiti-checkstyle</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <name>Wakamiti Checkstyle Checks</name>

    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
        <checkstyle.skip>true</checkstyle.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.puppycrawl.tools</groupId>
            <artifactId>checkstyle</artifactId>
            <version>${checkstyle.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>6.1.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpcore</artifactId>
                <version>4.4.16</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
