spring:
  application:
    name: Spring Sample App
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
    data: classpath:initial-data.sql


server:
  port: 9191