#!/bin/bash

#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#

if test -z "${KUKUMO_HOME}"
then
  export KUKUMO_HOME="/usr/local/share/kukumo"
fi
java -jar "${KUKUMO_HOME}/java-version-checker.jar" 11

if test $? -ne 0
then
  exit -2
fi

#java -Dlog4j.configurationFile=${KUKUMO_HOME}/log4j2.xml \
#   -javaagent:${KUKUMO_HOME}/kukumo-launcher.jar \
#   --module-path "${KUKUMO_HOME}/kukumo-launcher.jar:${KUKUMO_HOME}/lib" \
#   -cp "${KUKUMO_HOME}/lib-ext/*" \
#   -m kukumo.launcher/iti.kukumo.launcher.KukumoLauncher "$@"
java -Dlog4j.configurationFile=${KUKUMO_HOME}/log4j2.xml \
  -javaagent:${KUKUMO_HOME}/kukumo-launcher.jar \
  -classpath "${KUKUMO_HOME}/kukumo-launcher.jar:${KUKUMO_HOME}/lib/*:${KUKUMO_HOME}/lib-ext/*" \
  iti.kukumo.launcher.KukumoLauncher "$@"